import { ArrowUpRight, ArrowRight, Check, MoveDown } from 'lucide-react';
import PageMeta from '@/components/PageMeta';
import { DEMO_URL } from '@/lib/landing-theme';
import '@/styles/gaoz.css';

const contact = `${DEMO_URL}?text=${encodeURIComponent('Hola, quiero conversar sobre TOOL Sales Lab para GAOZ y definir el arranque del programa de 5 semanas.')}`;
const weeks = [
  { n:'01', title:'Commercial X-Ray', sub:'Encontrar el foco.', sessions:[
    {label:'SESIÓN 1 · DIAGNÓSTICO', title:'¿Dónde perdemos oportunidades? ¿Dónde podemos crecer?', copy:'Leemos juntos la operación para identificar cuellos de botella, fugas, dependencias y palancas de crecimiento.', result:'Mapa ejecutivo de oportunidades y prioridades comerciales.'},
    {label:'SESIÓN 2 · SEGMENTACIÓN Y FOCO', title:'La mejor oportunidad puede estar en la cartera actual.', copy:'Segmentamos por recurrencia, potencial, ticket y línea comprada. Activamos upsell, cross-sell, resell y reactivación; ponemos a prueba el potencial de tomografía y resonancia.', result:'Mapa de cartera, Top 20 con plan de acción y 5 equipos prioritarios con estrategia de salida.'}]},
  { n:'02', title:'Arquitectura del equipo', sub:'Dar claridad para actuar.', sessions:[
    {label:'SESIONES 3 Y 4 · ESTRUCTURA COMERCIAL', title:'Quién dirige. Quién vende. Quién decide.', copy:'Definimos la función del gerente comercial, responsabilidades de vendedores, ownership de cartera, reglas de decisión e interacción con Dirección. Cada compromiso tendrá un responsable.', result:'Estructura comercial v1 y scorecards por rol.'}]},
  { n:'03', title:'Construir el método', sub:'Hacer repetible lo que funciona.', sessions:[
    {label:'SESIÓN 5 · MÉTODO COMERCIAL GAOZ', title:'Una forma común de vender.', copy:'De cada vendedor con su propio método a un proceso compartido, con criterios claros para avanzar.', flow:'Lead → Calificación → Diagnóstico → Solución → Propuesta → Negociación → Cierre', result:'Sales Process GAOZ v1.'},
    {label:'SESIÓN 6 · METAS, PIPELINE Y RITMO', title:'Una meta que se traduce en acciones.', copy:'Construimos KPIs, forecast, Top Deals, Weekly Comercial y compromisos. La gestión empieza por saber qué mover cada semana.', flow:'Venta anual → Venta mensual → Pipeline necesario → Oportunidades → Actividad comercial', result:'Commercial Scorecard + ritmo de operación.'}]},
  { n:'04', title:'Vender mejor', sub:'Llevar el sistema a la conversación.', sessions:[
    {label:'SESIÓN 7 · MINDSET & CULTURA', title:'El sistema funciona cuando cambian los comportamientos.', copy:'Trabajamos la mentalidad que sostiene los resultados: aprendizaje, accountability y ejecución consistente. Identificamos qué comportamientos necesita GAOZ y cuáles frenan al equipo.', result:'Comportamientos comerciales que sostienen el nuevo sistema.'},
    {label:'SESIÓN 8 · DEAL LAB', title:'Negocios reales. Conversaciones decisivas.', copy:'Simulaciones y clínicas sobre precio, competencia, descuento, múltiples decisores, comparación de equipos, urgencia, financiamiento y seguimiento.', result:'Playbook de objeciones + plan para oportunidades críticas.'}]},
  { n:'05', title:'Instalar y escalar', sub:'Dejar listo el siguiente ciclo.', sessions:[
    {label:'SESIÓN 9 · CRM & CONTROL ROOM', title:'Un solo lugar para la verdad comercial.', copy:'Con el proceso definido, estructuramos etapas, campos, actividades, responsables, alertas, forecast y dashboards en el diseño del CRM.', result:'CRM Blueprint + sistema de seguimiento.'},
    {label:'SESIÓN 10 · ESTRATEGIA COMERCIAL', title:'Un norte claro para los próximos 60 días.', copy:'Alineamos visión, metas y objetivos del negocio con el mercado donde competir y el cliente ideal. Revisamos qué funcionó, qué corregir y cómo avanzar.', result:'Roadmap de estrategia comercial a 60 días.'}]},
];
const pillars = [['Estrategia','Dónde jugar y enfocar recursos.'],['Estructura','Quién es responsable de qué.'],['Método','Cómo se vende.'],['Gestión','Cómo se mide y dirige.'],['Herramientas','Con qué vende el equipo.'],['Ritmo','Cómo se mejora cada semana.']];
const businessValue = [
  ['01','Enfocar el esfuerzo donde puede generar negocio.','Top 20 + segmentación de cartera','El equipo sabrá a qué clientes dedicar tiempo, qué ofrecerles y cuál es el siguiente paso.','Priorizar oportunidades por potencial y probabilidad.'],
  ['02','Dar salida comercial al inventario.','Estrategia para 5 equipos prioritarios','Cada equipo seleccionado tendrá una propuesta y un segmento al cual dirigir la conversación comercial.','Pasar de esperar demanda a trabajar oportunidades específicas.'],
  ['03','Defender el valor antes de negociar el precio.','Deal Lab + playbook de objeciones','El equipo practicará cómo responder a comparaciones, descuentos y múltiples decisores sobre negocios que hoy tiene abiertos.','Preparar la negociación y cuidar el margen.'],
  ['04','Dirigir sin perseguir cada actualización.','Roles + scorecard + Weekly Comercial','Dirección podrá revisar prioridades, bloqueos y compromisos con responsables y un método común.','Intervenir donde hace falta y dar autonomía al equipo.'],
];
const weekValue: Record<string,string> = {'01':'Decidir qué oportunidades e inventario merecen atención primero.','02':'Resolver decisiones con responsables claros, reduciendo la dependencia de Dirección.','03':'Detectar dónde se frena una venta y qué actividad necesita la meta.','04':'Llegar a oportunidades críticas con una negociación preparada y compromisos claros.','05':'Dar continuidad al método con seguimiento y prioridades para los próximos 60 días.'};
function CTA({children='Conversemos sobre el arranque'}:{children?:React.ReactNode}) { return <a className="gz-button" href={contact} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={19}/></a>; }
export default function Gaoz(){return <div className="gz">
  <PageMeta title="TOOL Sales Lab · GAOZ | Sistema comercial en 5 semanas" description="Convierte 27 años de experiencia de GAOZ en un sistema comercial enfocado, medible y repetible. 5 semanas, 10 sesiones y oportunidades reales desde el inicio."/>
  <a className="gz-skip" href="#gaoz-main">Saltar al contenido</a>
  <header className="gz-nav"><a href="/" className="gz-brand" aria-label="Ir a la web principal de TOOL">TOOL<span>SALES LAB</span></a><nav aria-label="Navegación del programa"><a href="#valor">El valor para GAOZ</a><a href="#programa">Las 5 semanas</a><a href="#sistema">El resultado</a></nav><a href={contact} target="_blank" rel="noopener noreferrer" className="gz-nav-cta">Hablemos <ArrowUpRight size={16}/></a></header>
  <main id="gaoz-main">
    <section className="gz-hero"><div className="gz-hero-copy"><div className="gz-eyebrow"><span className="gz-dot"/> TOOL SALES LAB · DISEÑADO PARA GAOZ</div><h1>27 años de experiencia.<br/><span>El siguiente paso<br/>es un sistema.</span></h1><p>En 5 semanas, convertir esa experiencia en <strong>oportunidades priorizadas, un equipo con método y una Dirección con visibilidad.</strong> Trabajando sobre la cartera, el inventario y los negocios que GAOZ tiene hoy.</p><div className="gz-actions"><CTA>Identifiquemos dónde está el valor</CTA><a className="gz-text-link" href="#programa">Explorar el programa <MoveDown size={16}/></a></div><div className="gz-hero-note">5 semanas <span> / </span> 10 sesiones <span> / </span> Tu operación real</div></div>
    <div className="gz-system-visual" aria-label="Del conocimiento de GAOZ a un sistema comercial: foco, equipo, método, ejecución y control"><div className="gz-visual-head"><span>GAOZ / COMMERCIAL OS</span><span>VERSIÓN 1.0</span></div><div className="gz-visual-title">La experiencia<br/>se vuelve <em>sistema.</em></div><div className="gz-system-steps">{['Foco comercial','Equipo alineado','Método compartido','Mejor ejecución','Control y dirección'].map((s,i)=><div key={s}><span>0{i+1}</span><strong>{s}</strong><ArrowUpRight size={17}/></div>)}</div><div className="gz-visual-foot"><span className="gz-dot"/> ACTIVACIÓN DESDE LA SEMANA 01</div></div></section>
    <div className="gz-proof"><span>EL PUNTO DE PARTIDA ES GAOZ</span><strong>Clientes reales</strong><span>+</span><strong>Oportunidades reales</strong><span>+</span><strong>Inventario y datos reales</strong></div>
    <section className="gz-section gz-context" id="enfoque"><div><div className="gz-eyebrow">01 / EL SIGUIENTE NIVEL</div><h2>La experiencia abrió puertas.<br/><span>El sistema permite avanzar juntos.</span></h2></div><div><p>Durante 27 años, GAOZ ha construido relaciones, experiencia comercial y conocimiento técnico. Ese es el punto de partida.</p><p>El siguiente paso es que esa capacidad viva en toda la organización: que cada oportunidad tenga seguimiento, cada vendedor tenga foco y la Dirección tenga visibilidad.</p><p className="gz-statement">Que vender deje de depender de personas específicas y se convierta en una capacidad del negocio.</p></div></section>
    <section className="gz-value gz-section" id="valor"><div className="gz-section-head"><div><div className="gz-eyebrow">EL VALOR PARA EL NEGOCIO</div><h2>Más claridad para decidir.<br/><span>Más capacidad para ejecutar.</span></h2></div><p>El valor de cada herramienta está en lo que le permite hacer a GAOZ con sus oportunidades reales.</p></div><div className="gz-value-grid">{businessValue.map(([n,title,deliverable,copy,value])=><article key={n}><span className="gz-value-index">{n} / CAPACIDAD COMERCIAL</span><h3>{title}</h3><p>{copy}</p><div className="gz-value-deliverable"><span>LO CONSTRUIMOS CON</span><strong>{deliverable}</strong></div><div className="gz-value-bottom"><ArrowUpRight size={20}/><span>{value}</span></div></article>)}</div></section>
    <section className="gz-example"><div><div className="gz-eyebrow">ASÍ SE TRADUCE A LA OPERACIÓN</div><h2>Una oportunidad necesita<br/><span>algo más que seguimiento.</span></h2><p>Ejemplo ilustrativo de cómo se trabajaría una oportunidad de equipo médico. La información se completa y valida con el equipo de GAOZ.</p></div><div className="gz-example-path"><div><span>EL PUNTO DE PARTIDA</span><h3>“La propuesta ya se envió.”</h3><p>Eso todavía no permite saber qué tan cerca está el cierre ni qué necesita el cliente para decidir.</p></div><ArrowRight aria-hidden="true"/><div><span>CON EL MÉTODO GAOZ</span><h3>Un siguiente paso verificable.</h3><ul><li>Necesidad y criterios de compra confirmados.</li><li>Decisores y objeciones identificados.</li><li>Responsable, próxima acción y fecha acordados.</li><li>Etapa sustentada en evidencia del cliente.</li></ul></div></div><p className="gz-example-conclusion"><strong>El valor:</strong> el vendedor sabe qué destrabar; el gerente sabe dónde apoyar; Dirección puede distinguir actividad de avance comercial.</p></section>
    <section className="gz-wins"><div className="gz-section-head"><div><div className="gz-eyebrow">EL SISTEMA EMPIEZA TRABAJANDO</div><h2>La primera semana<br/>ya tiene movimiento.</h2></div><p>Construimos mientras ejecutamos.<br/>Estas son las primeras tres acciones.</p></div><div className="gz-win-grid">{[['01','Ver con claridad','Identificar los cuellos de botella y los potenciadores de crecimiento.','Diagnóstico accionable'],['02','Concentrar el esfuerzo','Priorizar las 20 oportunidades con mayor probabilidad y valor.','Top 20 + plan de acción'],['03','Mover el inventario','Definir campañas específicas para 5 equipos prioritarios.','Estrategia de salida']].map(([n,t,c,r])=><article key={n}><span className="gz-win-num">{n}<ArrowUpRight/></span><h3>{t}</h3><p>{c}</p><div><Check size={16}/>{r}</div></article>)}</div></section>
    <section className="gz-section gz-program" id="programa"><div className="gz-section-head"><div><div className="gz-eyebrow">02 / LA RUTA DE TRABAJO</div><h2>Cinco semanas.<br/><span>Un cambio en la forma de vender.</span></h2></div><p>10 sesiones conectadas.<br/>Cada semana construye sobre la anterior.</p></div><div className="gz-week-nav" aria-label="Ir a una semana">{weeks.map(w=><a key={w.n} href={'#semana-'+w.n}><span>{w.n}</span>{w.title}<ArrowRight size={15}/></a>)}</div>{weeks.map(w=><article className="gz-week" id={'semana-'+w.n} key={w.n}><div className="gz-week-title"><span className="gz-week-number">{w.n}</span><div className="gz-eyebrow">SEMANA {w.n}</div><h3>{w.title}</h3><p>{w.sub}</p><div className="gz-week-value"><strong>PARA EL NEGOCIO</strong>{weekValue[w.n]}</div></div><div className="gz-sessions">{w.sessions.map(s=><section className="gz-session" key={s.label}><div className="gz-eyebrow">{s.label}</div><h4>{s.title}</h4><p>{s.copy}</p>{'flow' in s && <div className="gz-flow">{s.flow}</div>}<div className="gz-result"><Check size={17}/><p><strong>Resultado</strong>{s.result}</p></div></section>)}</div></article>)}</section>
    <section className="gz-delivery" id="sistema"><div className="gz-delivery-intro"><div className="gz-eyebrow">03 / LO QUE SE QUEDA EN GAOZ</div><h2>El aprendizaje<br/>se convierte<br/>en <span>operación.</span></h2><p>Al terminar, GAOZ se queda con un sistema comercial propio. Y habrá empezado a utilizarlo desde la primera semana.</p><div className="gz-os-label"><span className="gz-dot"/> GAOZ COMMERCIAL OPERATING SYSTEM v1</div></div><div className="gz-pillars">{pillars.map(([t,c],i)=><div key={t}><span>0{i+1}</span><div><h3>{t}</h3><p>{c}</p></div><ArrowUpRight size={21}/></div>)}</div></section>
    <section className="gz-section gz-evidence"><div className="gz-section-head"><div><div className="gz-eyebrow">CÓMO HACER VISIBLE EL AVANCE</div><h2>El valor se revisa<br/><span>con evidencia, semana a semana.</span></h2></div><p>Partimos de una línea base de GAOZ y acordamos metas de seguimiento. Así distinguimos lo construido, lo utilizado y su efecto comercial.</p></div><div className="gz-evidence-grid"><article><span>01 / LO QUE SE CONSTRUYE</span><h3>Capacidad instalada</h3><p>Top 20 con plan, roles definidos, proceso con criterios de avance y scorecard comercial.</p><strong>Evidencia: entregables revisados con el equipo.</strong></article><article><span>02 / LO QUE SE UTILIZA</span><h3>Ejecución observable</h3><p>Oportunidades con responsable y próxima acción, compromisos cumplidos y reuniones comerciales con decisiones.</p><strong>Evidencia: revisión semanal del pipeline y los compromisos.</strong></article><article><span>03 / LO QUE CAMBIA</span><h3>Impacto comercial</h3><p>Avance de oportunidades, conversión entre etapas, descuentos, duración del ciclo y movimiento del inventario prioritario.</p><strong>Evidencia: comparación con la línea base, según los datos y el ciclo de venta.</strong></article></div><p className="gz-evidence-note">Las cinco semanas permiten construir y empezar a utilizar el sistema. Los cierres y el impacto en ventas se evalúan según la evolución de las oportunidades y continúan en el roadmap de 60 días.</p></section>
    <section className="gz-final" id="arranque"><div className="gz-eyebrow">EL SIGUIENTE CAPÍTULO DE GAOZ</div><h2>Lo que tomó 27 años construir<br/>merece un sistema para <span>crecer.</span></h2><p>Pongamos sobre la mesa la cartera, el inventario y los negocios abiertos.<br/>Identifiquemos dónde puede aportar más valor el programa y qué medir desde el inicio.</p><CTA>Hablemos de las oportunidades de GAOZ</CTA><div className="gz-final-note">Conversación directa con TOOL por WhatsApp</div></section>
  </main><footer className="gz-footer"><a className="gz-brand" href="/">TOOL<span>SALES LAB</span></a><span>Una propuesta para GAOZ · Versión cliente 01</span><a href="#programa">Volver al programa ↑</a></footer>
 </div>}

