import { ArrowLeft, ArrowRight, ArrowUpRight } from 'lucide-react';
import PageMeta from '@/components/PageMeta';
import '@/styles/gaoz-diagnosis.css';

const source = 'https://app.notion.com/p/GAOZ-3c77f5fdb8aa80dca274e459e7ab5d8b';
const strengths = [['Experiencia técnica','Conocimiento del equipo médico y capacidad de capacitación.'],['Relación con clientes','La recompra y el seguimiento cercano ya son fortalezas.'],['Oferta multimarca','Equipos nuevos y reacondicionados para distintas necesidades.']];
const indicators = [['Ventas y margen','Cuánto vendemos y con qué rentabilidad.'],['Pipeline y conversión','Qué oportunidades avanzan y dónde se detienen.'],['Ciclo de venta','Cuánto tarda una oportunidad en cerrarse.'],['Recompra e inventario','Qué cartera se reactiva y qué equipos se mueven.']];
const gaps = [
  ['Foco','8 líneas de producto','Priorizar segmentos, cuentas y productos.'],
  ['Equipo','Autoridad comercial por aclarar','Definir quién decide y quién responde.'],
  ['Datos','Histórico disponible','Convertirlo en decisiones y seguimiento.'],
  ['Cartera','Recompra y servicio fuertes','Activar renovación, venta cruzada y referidos.'],
];
const targets = [
  ['90%','Oportunidades activas visibles','Meta propuesta · primera semana',90],
  ['100%','Top 20 con próxima acción y fecha','Meta propuesta · primera semana',100],
  ['80%','Contacto con 20 clientes históricos','Meta propuesta · segunda semana',80],
] as const;

export default function GaozDiagnosis(){return <div className="gd">
  <PageMeta title="Diagnóstico comercial GAOZ | TOOL" description="Síntesis del diagnóstico comercial de GAOZ: situación actual, prioridades y primeras acciones para construir un sistema de ventas medible."/>
  <a className="gd-skip" href="#diagnostico">Saltar al diagnóstico</a>
  <header className="gd-header"><a className="gd-logo" href="/">TOOL</a><a href="/gaoz/"><ArrowLeft size={16}/> Volver al Sales Lab</a></header>
  <main id="diagnostico">
    <section className="gd-intro"><span className="gd-label">GAOZ / DIAGNÓSTICO COMERCIAL 2026</span><h1>La experiencia está.<br/><span>Falta conectar el sistema.</span></h1><p>La hipótesis: el principal cuello de botella está en cómo se organiza la venta, más que en el mercado.</p><small>Lectura inicial · Documento del 29 de agosto de 2026 · Por validar con el equipo</small></section>
    <nav className="gd-route" aria-label="Ruta del diagnóstico"><a href="#situacion"><b>01</b> Qué vemos <ArrowRight size={16}/></a><a href="#prioridades"><b>02</b> Qué ordenar <ArrowRight size={16}/></a><a href="#acciones"><b>03</b> Cómo empezar <ArrowRight size={16}/></a></nav>
    <section className="gd-section" id="situacion"><div className="gd-heading"><span className="gd-label">01 / SITUACIÓN ACTUAL</span><h2>Una operación que aún<br/>depende de personas clave.</h2></div><div className="gd-current"><figure className="gd-concentration"><figcaption>Concentración de ventas reportada</figcaption><div className="gd-big">≈60%<span>concentrado en el fundador</span></div><div className="gd-stack" role="img" aria-label="Aproximadamente 60 por ciento de las ventas concentradas en el fundador; 40 por ciento restante"><span/><span/></div><div className="gd-legend"><span>Fundador · ≈60%</span><span>Resto · ≈40%</span></div><p>El reto es transferir relaciones, conocimiento y responsabilidad de forma gradual.</p><small>Estimación del diagnóstico, no una medición auditada.</small></figure><div className="gd-gaps">{gaps.map(([title,current,action])=><article key={title}><span>{title}</span><div><h3>{current}</h3><p>{action}</p></div></article>)}</div></div></section>
    <section className="gd-section"><div className="gd-heading"><span className="gd-label">LO QUE YA FUNCIONA</span><h2>La base para crecer ya existe.</h2></div><div className="gd-strengths">{strengths.map(([title,copy])=><article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="gd-hypothesis"><span className="gd-label">OPORTUNIDAD COMERCIAL</span><h3>Hacer del servicio una fuente de nuevas ventas.</h3><p>Cada visita técnica puede detectar reemplazos, equipos complementarios, expansión o referidos. El paso pendiente es registrar esas señales y asignarles seguimiento.</p></div></section>
    <section className="gd-section" id="prioridades"><div className="gd-heading"><span className="gd-label">02 / PRIORIDADES</span><h2>Primero ordenar.<br/>Después escalar.</h2></div><ol className="gd-sequence">{[['Responsables','Autoridad y cartera claras.'],['Datos','Oportunidades y clientes visibles.'],['Foco','Elegir dónde concentrar el esfuerzo.'],['Seguimiento','Próxima acción, fecha y revisión.']].map(([t,p],i)=><li key={t}><span>0{i+1}</span><h3>{t}</h3><p>{p}</p>{i<3 && <ArrowRight aria-hidden="true" size={18}/>}</li>)}</ol><div className="gd-decisions"><article><h3>Dar autoridad a la gerencia comercial.</h3><p>Alinear quién dirige al equipo, quién decide y quién responde por los resultados. Transferir cuentas y relaciones gradualmente, con responsabilidades explícitas.</p></article><article><h3>Definir el proceso antes del CRM.</h3><p>HubSpot debe reflejar una forma común de vender. Empezar por las oportunidades activas, con dueño, etapa y siguiente acción.</p></article></div><div className="gd-hypothesis"><span className="gd-label">APUESTA POR VALIDAR</span><h3>Tomografía y resonancia</h3><p>Probar con 10 cuentas antes de escalar. Comparar margen, conversión y ciclo de venta con el resto del portafolio.</p></div><div className="gd-segments"><span className="gd-label">SEGMENTOS A COMPARAR</span><div><span>Hospitales</span><span>Médicos y centros de diagnóstico</span><span>Distribuidores</span></div><p>Decidir dónde invertir a partir de ticket, margen, conversión, ciclo de venta y recompra.</p></div></section>
    <section className="gd-section" id="acciones"><div className="gd-heading"><span className="gd-label">03 / PRIMERAS ACCIONES</span><h2>Dos semanas para<br/>ver, priorizar y actuar.</h2><p>Sprint sugerido en el diagnóstico. Sus metas se validan al arranque y no representan resultados alcanzados.</p></div><div className="gd-sprint"><article><span className="gd-label">SEMANA 1 · VER Y ORDENAR</span><h3>Pipeline + Top 20 + inventario</h3><ul><li>Cargar las oportunidades activas en CRM.</li><li>Priorizar 20 negocios con responsable y fecha.</li><li>Definir oferta y clientes para 5 equipos.</li></ul></article><article><span className="gd-label">SEMANA 2 · ACCIONAR Y APRENDER</span><h3>Cartera + cuentas + revisión</h3><ul><li>Reactivar 20 clientes con potencial.</li><li>Contactar 10 cuentas de tomografía / RM.</li><li>Revisar avances y elegir 3 prioridades.</li></ul></article></div><figure className="gd-targets"><figcaption>Metas propuestas para el sprint</figcaption>{targets.map(([value,title,note,width])=><div className="gd-target" key={title}><div><strong>{title}</strong><span>{value}</span></div><div className="gd-track" role="img" aria-label={`${title}: meta de ${value}`}><span style={{width:width+'%'}}/></div><small>{note}</small></div>)}</figure></section>
    <section className="gd-north"><span className="gd-label">LA SEÑAL DE AVANCE</span><h2>Más ventas gestionadas por el equipo,<br/>sin intervención directa de los socios.</h2><p>Indicador recomendado. La línea base y la meta están por definir.</p><div className="gd-cadence"><span>Lunes · prioridades</span><ArrowRight size={18}/><span>Semana · ejecución</span><ArrowRight size={18}/><span>Viernes · resultados</span></div></section>
    <section className="gd-section"><div className="gd-heading"><span className="gd-label">CÓMO MEDIR EL CAMBIO</span><h2>Pocos indicadores.<br/>Decisiones claras.</h2><p>Construir primero la línea base con el histórico comercial. Después acordar metas y revisar avances semanalmente.</p></div><div className="gd-indicators">{indicators.map(([title,copy])=><article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="gd-hypothesis"><span className="gd-label">PARA UNA SIGUIENTE ETAPA</span><p>Con el proceso estable, evaluar incentivos, especialización por producto y efectividad de canales. Los cambios en comisiones requieren conocer margen, dificultad y prioridad comercial.</p></div></section>
    <section className="gd-next"><div><span className="gd-label">DEL DIAGNÓSTICO A LA ACCIÓN</span><h2>Esta es la base del Sales Lab.</h2><p>5 semanas para construir y empezar a usar el sistema comercial de GAOZ.</p></div><a className="gd-button" href="/gaoz/#programa">Ver el plan de trabajo <ArrowUpRight size={18}/></a></section>
  </main><footer className="gd-footer"><span>TOOL · GAOZ</span><a href={source} target="_blank" rel="noopener noreferrer">Consultar diagnóstico en Notion ↗</a></footer>
 </div>}
